reports/template.md

{GUILD} Report - July 2021

---

reports/eoseouldotio/2021-07.md

Update EOSeoul reports 2021-07

Update EOSeoul reports 2021-07

---

reports/waxswedenorg/2021-07.md

Added sw/eden update

---

reports/eosdublinwow/2021-07.md

Added Guild Report for July 2021

eosDublin Report - July 2021

---

reports/eosphereiobp/2021-07.md

This is the initial OIG Submission since moving over to GitHub

EOSphere Guild July 2021 OIG Submission

---

reports/eosarabianet/2021-07.md

EOS Arabia Report - July 2021

---

reports/pink.gg/2021-07.md

pink.gg Report - July 2021

---

reports/ledgerwiseio/2021-07.md

Ledgerwise Report - July 2021

---

reports/blokcrafters/2021-07.md

BlokCrafters Report - July 2021

---

reports/ivote4waxusa/2021-07.md

WAXUSA - July 2021

---

reports/amsterdamwax/2021-07.md

Added guild report for EOS Amsterdam for July 2021

EOS Amsterdam Report - July 2021

---

reports/waxswedenorg/2021-07.md
reports/waxswedenorg/waxswedenorg-update-aug-2021.md

Sw/eden August Update

---

reports/eoseouldotio/2021-08.md

Added guild report August 2021

EOSeoul - August 2021

---

reports/dapplica/Dapplica Report - August 2021.md

Dapplica Report - August 2021

---

reports/eosiodetroit/2021-08.md

EOS DETROIT August 2021 OIG Update

August 2021 OIG Update

---

reports/amsterdamwax/2021-08.md

Added guild report August 2021

EOS Amsterdam - August 2021

---

reports/teamgreymass/2021-08.md

Let me know if I screwed this up somehow! 😉

Greymass - August Report

---

reports/eoseouldotio/2021-09.md

Added guild report September 2021

EOSeoul - September 2021

---

reports/waxswedenorg/waxswedenorg-update-september-2021.md

The sw/eden September IG update

WAX sw/eden september update

---

reports/alohaeosprod/2021-09.md

Aloha EOS Report - September 2021

Aloha EOS Report - September 2021

---

reports/eosarabianet/2021-09.md

Added guild report for September  2021

EOS Arabia Report - September 2021

---

reports/blokcrafters/BlokCrafters Guild - September 2021.md

BlokCrafters Report - September 2021

---

reports/waxswedenorg/waxswedenorg-update-October-2021.md

sw/eden October Update

---

reports/eosarabianet/2021-10.md

Added EOS Arabia guild  report for Oct-2021

EOS Arabia Report - Oct 2021

---

reports/amsterdamwax/2021-10.md

EOS Amsterdam Report - October 2021

EOS Amsterdam Report - October 2021

---

reports/waxswedenorg/waxswedenorg-update-November-2021.md

Added the November Guild update for WAX sw/eden

Added the November Guild update for WAX sw/eden

---

reports/tokengamerio/2021-11.md

initial guild submission

---

reports/eosarabianet/2021-11.md

Added Guild report for November 2021

EOS Arabia - November 2021

---

reports/eosdacserver/2021-11.md

eosdacserver November 2021 report

eosdacserver Report - November 2021

---

reports/amsterdamwax/2021-11.md

EOS Amsterdam Report - November 2021

---

reports/alohaeosprod/2021-11.md

Aloha EOS Report - November 2021

Aloha EOS Report - November 2021

---

reports/blokcrafters/2022-01.md

Our WAX Guild submission report for January 2022

BlokCrafters Report - January 2022

---

reports/eosdacserver/2022-01.md

eosDAC OIG Submission - January 2022

eosDAC OIG submission - January 2022

---

reports/neftyblocks/report-no-1.md

NeftyBlocks report-1 added to the repository

NeftyBlocks report number 1 | 2021-12

---

reports/alohaeosprod/2022-01.md

Aloha EOS Report - January 2022

Aloha EOS Report - January 2022

---

reports/waxswedenorg/waxswedenorg-update-January-2022.md

The sw-eden January 2022 Guild Update

sw-eden January 2022 Update

---

reports/amsterdamwax/2022-01.md

EOS Amsterdam report - January 2022

EOS Amsterdam report - January 2022

---

reports/eosarabianet/2022-01.md

Added guild report for Jan-2022

EOS Arabia Report - Jan-2022

---

reports/neftyblocks/report-no-1.md

Guild.nefty report #1

---

reports/cryptolions1/2022-02 .md

Create 2022-02 .md

---

reports/eosarabianet/2022-02.md

Added guild report for  February 2022

EOS Arabia Report - February 2022

---

reports/alohaeosprod/2022-02.md

Aloha EOS Report - February 2022

Aloha EOS Report - February 2022

---

reports/waxswedenorg/waxswedenorg-update-February-2022.md

The sw/eden February guild update.

waxsweden-feb-update

---

reports/blokcrafters/2022-04.md

Our report for the rating period ending April 15th, 2022.

BlokCrafters Report - April 2022

---

reports/eosarabianet/2022-04.md

Added guild report for April 2022

EOS Arabia report - April 2022

---

reports/amsterdamwax/2022-03.md

EOS Amsterdam Report - March 2022

---

reports/alohaeosprod/2022-04.md

Aloha EOS Report - April 2022

---

reports/waxswedenorg/03-2022.md

sw/eden - April 2022

---

reports/eosarabianet/2022-05.md

Added guild report for May 2022

EOS Arabia Report -May 2022

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md

Aloha EOS Report - May 2022

---

reports/dapplica/2022-05.md

Created May 2022 report

---

reports/eosdacserver/2022-07.md

eosdacserver - July 2022 OIG Submission

eosdacserver - July 2022

---

reports/defibox/2022-06.md

2022-06 Guild report from Defibox

Defibox Report - July 2022

---

reports/eosarabianet/2022-07.md

Added guild report for July 2022

EOS Arabia Report - July 2022

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md

Aloha EOS Report - July 2022

---

reports/eosriobrazil/2022-08

EOS Rio Report August 2022

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md

Aloha EOS Report - August 2022

Aloha EOS Report - August 2022

---

reports/waxswedenorg/2022-09.md

sw/edens update for September 2022

WAX Sw/eden - September 2022 Update

---

reports/eosarabianet/2022-07.md
reports/eosarabianet/2022-08.md

Added guild report for August 2022

EOS Arabia Report - August 2022

---

reports/tokengamerio/Token Gamer BP October 2022 Report.md

Token Gamer BP October 2022 Report.md

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md

Aloha EOS Report - October 2022

Aloha EOS Report - October 2022

---

reports/eosarabianet/2022-07.md
reports/eosarabianet/2022-08.md
reports/eosarabianet/2022-10.md

Added EOS Arabia report for October 2022

EOS Arabia Report - October 2022

---

reports/eosdacserver/2022-07.md
reports/eosdacserver/2022-08.md
reports/eosdacserver/2022-10.md
reports/eosdacserver/Appeal - 2022-10.md

EOSDACSERVER - OCT 2022 Report

EOSDACSERVER - OCT 2022

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md

Aloha EOS Report - November 2022

Aloha EOS Report - November 2022

---

reports/eosdacserver/2022-07.md
reports/eosdacserver/2022-08.md
reports/eosdacserver/2022-10.md
reports/eosdacserver/2022-11.md
reports/eosdacserver/Appeal - 2022-10.md

eosdacserver report - Nov 2022

eosdacserver report - Nov 2022

---

reports/waxswedenorg/2022-11.md

Our WAX Update for November 2022

sw/eden November 2022 Update

---

reports/waxswedenorg/2023-01.md

wax sw/eden January Update for the OIG

sw/eden January update 2023

---

reports/taco/2023-01.md

Hi,
this is the first Taco pull request with the BP application report under the folder reports/taco. 
Thanks.

Taco BP Application

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md
reports/alohaeosprod/2023-01.md

Aloha EOS Report - January 2023

Aloha EOS Report - January 2023

---

reports/waxswedenorg/2023-02.md

waxswedenorg OIG Update for February 2023

sw/eden Update - February 2023

---

reports/eosdacserver/2022-07.md
reports/eosdacserver/2022-08.md
reports/eosdacserver/2022-10.md
reports/eosdacserver/2022-11.md
reports/eosdacserver/2023-01.md
reports/eosdacserver/2023-02.md
reports/eosdacserver/Appeal - 2022-10.md

EOSDACSERVER - OIG Submission Feb 2023

---

reports/defibox/2023-02.md

Defibox - February Update

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md
reports/alohaeosprod/2023-01.md
reports/alohaeosprod/2023-02.md
reports/alohaeosprod/2023-04.md

Aloha EOS Report - April 2023

---

reports/waxswedenorg/2023-04.md

sw/eden April update - 2023

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md
reports/alohaeosprod/2023-01.md
reports/alohaeosprod/2023-02.md
reports/alohaeosprod/2023-04.md
reports/alohaeosprod/2023-05.md

Aloha EOS Report - May 2023

---

reports/eosarabianet/2023-05.md

Added EOS Arabia Report for May 2023

EOS Arabia Report - May 2023

---

reports/defibox/2023-04.md

Add 2023-04 report

---

reports/blokcrafters/2023-07-15.md

Blokcrafters 2023-07-15 IG report.

Blokcrafters 2023-07-15.md Update

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md
reports/alohaeosprod/2023-01.md
reports/alohaeosprod/2023-02.md
reports/alohaeosprod/2023-04.md
reports/alohaeosprod/2023-05.md
reports/alohaeosprod/2023-07.md

Aloha EOS Report - July 2023

---

reports/waxswedenorg/2023-07.md

sw/eden - July 2023

---

reports/alohaeosprod/2022-04.md
reports/alohaeosprod/2022-05.md
reports/alohaeosprod/2022-07.md
reports/alohaeosprod/2022-08.md
reports/alohaeosprod/2022-10.md
reports/alohaeosprod/2022-11.md
reports/alohaeosprod/2023-01.md
reports/alohaeosprod/2023-02.md
reports/alohaeosprod/2023-04.md
reports/alohaeosprod/2023-05.md
reports/alohaeosprod/2023-07.md
reports/alohaeosprod/2023-08.md

Aloha EOS Report - August 2023

Aloha EOS Report - August 2023

---

reports/waxswedenorg/2023-08.md

waxsweden guild update August 2023

sw/eden - August 2023

---

reports/wombat/2023-08.md

Initial submission of the BP application for Wombat Guild

Wombat Guild - Initial submission

---

reports/alohaeosprod/2023-10.md

Aloha EOS Report - October 2023

Aloha EOS Report - October 2023

---

reports/waxswedenorg/2023-10.md

sw/eden | October 2023 Guild Update

---

reports/eosarabianet/2023-10.md

Added guild  Report for  Oct 2023

EOS Arabia Report - Oct 2023

---

reports/eosdacserver/2023-10.md

EOSDACSERVER OIG SUBMISSION October 2023

EOSDACSERVER OIG SUBMISSION October 2023

---

reports/oneinacilian/2023-08.md
reports/oneinacilian/2023-10.md

Hopefully second time lucky! 
Please ignore 2023-08 and look at 2023-10.

OIAC October 2023 Update

---

reports/alohaeosprod/2023-10.md
reports/alohaeosprod/2023-11.md

Aloha EOS Report - November 2023

Aloha EOS Report - November 2023

---

reports/waxswedenorg/2023-11.md

Our Update for the last period

sw/eden 2023 November Update

---

reports/bp.alcor/November-2023.md

Alcor Guild Submission November 2023

November-2023.md

---

reports/waxswedenorg/2024-01.md

WAX sw/eden update January 2024

sw/eden update - January 2024

---

reports/eosdacserver/2024-01.md

EOSDACSERVER - Jan 2024

---

reports/bp.alcor/January-2024.md

Alcor January-2024.md

---

reports/alohaeosprod/2024-01.md

Aloha EOS Report - January 2024

Aloha EOS Report - January 2024

---

reports/wizardsguild/Wizards Guild January 2024 Report

Wizards Guild January 2024 report for OIG

Wizards Guild - January 2024

---

reports/eosarabianet/2024-01.md

Added Guild report for January  2024

EOS Arabia Report - January 2024

---

reports/waxswedenorg/2024-02.md

WAX sw/eden update for Feb 2024

sw/eden - February 2024

---

reports/guild.waxdao/2024-02.md

February report for guild.waxdao

guild.waxdao February 2024 Report

---

reports/eosdacserver/2024-02.md

EOSDACSERVER Feb 2024

---

reports/eosarabianet/2024-02.md

Added guild report for  Feb 2024

EOS Arabia Report - Feb 2024

---

reports/guild.waxdao/latest.md

Updated latest.md for guild.waxdao

WaxDAO BP April 2024 Report

---

reports/alohaeosprod/latest.md

Aloha EOS Report - April 2024

---

reports/waxswedenorg/latest.md

sw/eden April 2024

---

reports/eosdacserver/latest.md

eosdacserver april 2024

---

reports/eosarabianet/latest.md

Added EOS Arabia  - April 2024 submission.

EOS Arabia - April 2024 submission.

---

reports/eosiodetroit/latest.md

Please consider our maintenance on WAX Labs, we added our fixes and improvements to the last report but still received 0 points on WAX Labs.

DLT May 2024 Guild Report

---

reports/guild.nefty/latest.md

Neftyblocks May 2024 report

---

reports/guild.waxdao/latest.md

May 2024 report for guild.waxdao

May 2024 report for guild.waxdao

---

reports/eosarabianet/latest.md

Added Guild "EOS Arabia" report May 2024

EOS Arabia Guild Report | May 2024 | Update latest.md

---

reports/waxswedenorg/latest.md

sw/eden - May 2024

---

reports/alohaeosprod/latest.md

Aloha EOS Report - May 2024

---

reports/eosarabianet/latest.md

EOS Arabia Guild Report July 2024

EOS Arabia Guild Report | July 2024 | Update latest.md

---

reports/alohaeosprod/latest.md

Aloha EOS Report - July 2024

---

reports/cryptolions1/latest.md

Update latest.md for August

---

reports/alohaeosprod/latest.md

Aloha EOS Report - August 2024

Aloha EOS Report - August 2024

---

reports/guild.waxdao/latest.md

Updated guild.waxdao/latest.md

WaxDAO BP - August 2024

---

reports/eosarabianet/latest.md

Added EOS Arabia guild report August 2024

EOS Arabia August 2024 report

---

reports/eosdacserver/latest.md

EOSDACSERVER AUGUST 2024 UPDATE

EOSDACSERVER AUGUST 2024 UPDATE

---

reports/eosdacserver/latest.md

EOSDSERVER OCTOBER 2024 UPDATE

EOSDSERVER OCTOBER 2024 UPDATE

---

reports/eosiodetroit/latest.md

Detroit Ledger Technologies (eosiodetroit) report submission for October 2024

Detroit Ledger Technologies - October 2024

---

reports/waxswedenorg/latest.md

sw/eden - October 2024

---

reports/dapplica/2024-08.md
reports/dapplica/latest.md

Archived August report and updated Latest.md

Dapplica Report - October 2024

---

reports/alohaeosprod/latest.md

Aloha EOS Report - October 2024

Aloha EOS Report - October 2024

---

reports/guild.taco/latest.md

Hi, we started updating the report file 4 days ago - so I think you already merged some of the changes we were submitting to the latest.md in the last merge!

Taco Report October 2024

---

reports/eosarabianet/latest.md

Added EOS Arabia Guild report Oct 2024

EOS Arabia Guild Report | Oct 2024

---

reports/alohaeosprod/latest.md

Aloha EOS Report - 2024.11.10

---

reports/eosarabianet/latest.md

EOS Arabia Updated Guild report Nov 2024

EOS Arabia Guild Report | Nov 2024

---

reports/guild.waxdao/latest.md

Updated DefiLlama initiative in latest.md

guild.waxdao 2024-11-24

---

reports/amsterdamwax/latest.md

Includes all projects now, along with updated metrics

Update latest.md EOS Amsterdam

---

reports/eosdacserver/latest.md

EOSDACSERVER Nov - dec 2024 update

EOSDACSERVER Nov - dec 2024 update

---

reports/alohaeosprod/latest.md

Aloha EOS Report - 2025.01.04

---

reports/dapplica/latest.md

Dapplica Product Report - December 13th 2024.md

---

reports/waxmadrid111/latest.md

Nodeinspector and hyperion backup update.

Update latest.md  waxmadrid111

---

reports/oneinacilian/latest.md

IPFS Enhancements – February 2025
Added replication endpoint for content availability monitoring Introduced content distribution endpoint for improved redundancy Upgraded to Kubo v0.27.0 for enhanced routing and discovery Updated to Node.js 20.x LTS for better performance Locked NPM dependencies for reproducible builds
Improved provider discovery and content tracking
Enhanced logging and error handling for system maintenance

February 25 OIG Update - oneinacilian

---

reports/alohaeosprod/latest.md

Aloha EOS Report - 2025.02.20

---

reports/cryptolions1/latest.md

Update for March. Please note there will be two PRs simultaneously, one for Jan (forgot to upload in Jan) and one for March. Please create a file from each PR.. So there will be a file for January and another file for March.
Sorry for the inconvenience.

Update latest.md March, please note there can be two PRs simultaneously

---

reports/alohaeosprod/latest.md

Aloha EOS Report - 2025.04.07

---

reports/guild.nefty/latest.md

Neftyblocks May 2025 Report

---

reports/cryptolions1/latest.md

May report, one new project inside (number 7)

Update latest.md for May

---

reports/alohaeosprod/latest.md

Aloha EOS Report - 2025.05.21

---

reports/cryptolions1/latest.md

Update for April. Please note there are two PR not merged yet, one for Jan (forgot to upload in Jan) and one for March. Please create a file from each PR.. So there will be a file for January and another file for March. Sorry for the inconvenience.

Update for April

---

reports/cryptolions1/latest.md

Sorry missed to download this report in January. Downloading now with delay.

Update latest.md January 2025
